2025-05-05 22:17:03 [INFO] tests.auth.test_auth_api: Тест: Отсутствует поле login [test_auth_api.py:134]
2025-05-05 22:17:03 [INFO] core.http_client: Sending POST request to APIEndpoints.AUTH [http_client.py:73]
2025-05-05 22:17:03 [INFO] core.http_client: Received response 403 from http://localhost:4040/APIEndpoints.AUTH [http_client.py:80]
