INFO     tests.user.test_user_favourites_api:test_user_favourites_api.py:27 
Test: Успешное получение избранного (GET /api/user/favourites)
INFO     core.http_client:http_client.py:44 Sending GET request to /api/user/favourites with params: None
INFO     core.http_client:http_client.py:48 Received response 403 from http://localhost:4040/api/user/favourites