2025-04-22 04:22:37 [INFO] tests.conftest: Создание UserClient... [conftest.py:67]
2025-04-22 04:22:37 [INFO] tests.user.test_user_api: Тест: Получение данных пользователя без авторизации (GET /api/user) [test_user_api.py:85]
2025-04-22 04:22:37 [INFO] api.user.client: Вызов GET /api/user [client.py:99]
2025-04-22 04:22:37 [INFO] core.http_client: Sending GET request to /api/user with params: None [http_client.py:44]
2025-04-22 04:22:37 [INFO] core.http_client: Received response 403 from http://localhost:4040/api/user [http_client.py:48]
2025-04-22 04:22:37 [INFO] tests.user.test_user_api: Тест: Получение данных пользователя без авторизации (GET /api/user) [test_user_api.py:85]
2025-04-22 04:22:37 [INFO] api.user.client: Вызов GET /api/user [client.py:99]
2025-04-22 04:22:37 [INFO] core.http_client: Sending GET request to /api/user with params: None [http_client.py:44]
2025-04-22 04:22:37 [INFO] core.http_client: Received response 403 from http://localhost:4040/api/user [http_client.py:48]
2025-04-22 04:22:37 [INFO] tests.user.test_user_api: Тест: Получение данных пользователя без авторизации (GET /api/user) [test_user_api.py:85]
2025-04-22 04:22:37 [INFO] api.user.client: Вызов GET /api/user [client.py:99]
2025-04-22 04:22:37 [INFO] core.http_client: Sending GET request to /api/user with params: None [http_client.py:44]
2025-04-22 04:22:37 [INFO] core.http_client: Received response 500 from http://localhost:4040/api/user [http_client.py:48]
2025-04-22 04:22:37 [WARNING] utils.allure_utils: Ответ не является валидным JSON, аттачим как текст. [allure_utils.py:62]
2025-04-22 04:22:37 [INFO] tests.user.test_user_api: Тест: Получение данных пользователя без авторизации (GET /api/user) [test_user_api.py:85]
2025-04-22 04:22:37 [INFO] api.user.client: Вызов GET /api/user [client.py:99]
2025-04-22 04:22:37 [INFO] core.http_client: Sending GET request to /api/user with params: None [http_client.py:44]
2025-04-22 04:22:37 [INFO] core.http_client: Received response 500 from http://localhost:4040/api/user [http_client.py:48]
2025-04-22 04:22:37 [WARNING] utils.allure_utils: Ответ не является валидным JSON, аттачим как текст. [allure_utils.py:62]
2025-04-22 04:22:37 [INFO] tests.user.test_user_api: Тест: Получение данных пользователя без авторизации (GET /api/user) [test_user_api.py:85]
2025-04-22 04:22:37 [INFO] api.user.client: Вызов GET /api/user [client.py:99]
2025-04-22 04:22:37 [INFO] core.http_client: Sending GET request to /api/user with params: None [http_client.py:44]
2025-04-22 04:22:37 [INFO] core.http_client: Received response 403 from http://localhost:4040/api/user [http_client.py:48]
