{"uid":"a0b508da4074a001","name":"Тест успешного удаления запроса из избранного","fullName":"tests.user.test_user_api.TestUserAPI#test_remove_from_favourites_success","historyId":"ceac80401fd9e5cd9418de44e0277fcd","time":{"start":1746737206980,"stop":1746737206980,"duration":0},"description":"Проверяем удаление ранее добавленного элемента из избранного.","descriptionHtml":"<p>Проверяем удаление ранее добавленного элемента из избранного.</p>\n","status":"failed","statusMessage":"Failed: КРИТИЧЕСКАЯ ОШИБКА: He удалось выполнить сессионный логин для пользователя testUser4@test.com. Ошибка: The status was pending 200, but received 500. URL: http://localhost:4040/api/auth\nBody of the answer:\nPlanned Server Error","statusTrace":"The status was pending 200, but received 500. URL: http://localhost:4040/api/auth\nBody of the answer:\nPlanned Server Error\n\nDuring handling of the above exception, another exception occurred:\nКРИТИЧЕСКАЯ ОШИБКА: He удалось выполнить сессионный логин для пользователя testUser4@test.com. Ошибка: The status was pending 200, but received 500. URL: http://localhost:4040/api/auth\nBody of the answer:\nPlanned Server Error","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"pytestconfig","time":{"start":1746737204348,"stop":1746737204348,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_verify_url","time":{"start":1746737204349,"stop":1746737204349,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"delete_output_dir","time":{"start":1746737204349,"stop":1746737204349,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"base_url","time":{"start":1746737204349,"stop":1746737204349,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"playwright_instance","time":{"start":1746737204350,"stop":1746737204856,"duration":506},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"api_request_context","time":{"start":1746737204856,"stop":1746737204892,"duration":36},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"http_client","time":{"start":1746737204892,"stop":1746737204893,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"auth_client","time":{"start":1746737204893,"stop":1746737204893,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"auth_token","time":{"start":1746737206982,"stop":1746737207069,"duration":87},"status":"failed","statusMessage":"Failed: КРИТИЧЕСКАЯ ОШИБКА: He удалось выполнить сессионный логин для пользователя testUser4@test.com. Ошибка: The status was pending 200, but received 500. URL: http://localhost:4040/api/auth\nBody of the answer:\nPlanned Server Error\n","statusTrace":"  File \"/app/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/app/.venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/app/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/app/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/app/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/app/tests/conftest.py\", line 109, in auth_token_fixture\n    pytest.fail(\n    ~~~~~~~~~~~^\n        f\"КРИТИЧЕСКАЯ ОШИБКА: He удалось выполнить сессионный логин для пользователя \"\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        f\"{TEST_USER_LOGIN}. Ошибка: {e}\",\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        pytrace=False,\n        ^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/app/.venv/lib/python3.13/site-packages/_pytest/outcomes.py\", line 178, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n","steps":[],"attachments":[{"uid":"1f119d6e49d5cd81","name":"Status Code: 500","source":"1f119d6e49d5cd81.txt","type":"text/plain","size":3},{"uid":"5d2af9aeecf84df8","name":"Request URL","source":"5d2af9aeecf84df8.uri","type":"text/uri-list","size":30},{"uid":"a7f6b9c8696b62c7","name":"Response Headers (JSON)","source":"a7f6b9c8696b62c7.json","type":"application/json","size":309},{"uid":"e4eda6384a5df427","name":"Response Body (Text)","source":"e4eda6384a5df427.txt","type":"text/plain","size":20},{"uid":"e40d1067273dc79a","name":"Status response code: 500 (Expected: 200)","source":"e40d1067273dc79a.txt","type":"text/plain","size":3}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":5,"hasContent":true,"attachmentStep":false},{"name":"auth_token","time":{"start":1746737207091,"stop":1746737207186,"duration":95},"status":"passed","steps":[],"attachments":[{"uid":"10d5d8a7b76c564e","name":"Status Code: 200","source":"10d5d8a7b76c564e.txt","type":"text/plain","size":3},{"uid":"3dee0b698c1525e8","name":"Request URL","source":"3dee0b698c1525e8.uri","type":"text/uri-list","size":30},{"uid":"a2211a6df390dabf","name":"Response Headers (JSON)","source":"a2211a6df390dabf.json","type":"application/json","size":317},{"uid":"641d0c3f90bc8671","name":"Response Body (JSON)","source":"641d0c3f90bc8671.json","type":"application/json","size":224},{"uid":"c87196e64b160092","name":"Status response code: 200 (Expected: 200)","source":"c87196e64b160092.txt","type":"text/plain","size":3},{"uid":"b1e761bfe8b105d4","name":"Body of the answer (failed by AuthSuccessResponse)","source":"b1e761bfe8b105d4.json","type":"application/json","size":220}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":6,"hasContent":true,"attachmentStep":false},{"name":"authenticated_api_req_context","time":{"start":1746737207186,"stop":1746737207197,"duration":11},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"authenticated_http_client","time":{"start":1746737207197,"stop":1746737207197,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"authenticated_user_client","time":{"start":1746737207197,"stop":1746737207197,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"setup_favourite","time":{"start":1746737207197,"stop":1746737207267,"duration":70},"status":"skipped","statusMessage":"Skipped: He удалось добавить элемент в избранное для тестов удаления: The status was pending 200, but received 400. URL: http://localhost:4040/api/user/favourites\nBody of the answer:\nFailed to add request to favourites\n","statusTrace":"  File \"/app/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/app/.venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/app/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/app/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/app/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/app/tests/user/conftest.py\", line 28, in setup_favourite\n    pytest.skip(f\"He удалось добавить элемент в избранное для тестов удаления: {e}\")\n    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/.venv/lib/python3.13/site-packages/_pytest/outcomes.py\", line 160, in skip\n    raise Skipped(msg=reason, allow_module_level=allow_module_level)\n","steps":[{"name":"Добавление запроса в избранное","time":{"start":1746737207198,"stop":1746737207264,"duration":66},"status":"failed","statusMessage":"AssertionError: The status was pending 200, but received 400. URL: http://localhost:4040/api/user/favourites\nBody of the answer:\nFailed to add request to favourites\n","statusTrace":"  File \"/app/.venv/lib/python3.13/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/app/api/user/client.py\", line 63, in add_to_favourites\n    processed_response = self._handle_response(response, expected_status)\n  File \"/app/api/base_api.py\", line 69, in _handle_response\n    assert response.status == expected_status, (\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[],"attachments":[{"uid":"fedf7f7a60fbc344","name":"Status Code: 400","source":"fedf7f7a60fbc344.txt","type":"text/plain","size":3},{"uid":"c1d014bb49b33bfc","name":"Request URL","source":"c1d014bb49b33bfc.uri","type":"text/uri-list","size":41},{"uid":"dde09710231f61dc","name":"Response Headers (JSON)","source":"dde09710231f61dc.json","type":"application/json","size":309},{"uid":"a7774131e01016c0","name":"Response Body (Text)","source":"a7774131e01016c0.txt","type":"text/plain","size":35},{"uid":"827ac441fb5abacc","name":"Status response code: 400 (Expected: 200)","source":"827ac441fb5abacc.txt","type":"text/plain","size":3}],"parameters":[{"name":"payload","value":"AddToFavouritesPayload(request_id='test-fav-450f9a3b-3270-4512-8d26-ad943fa28a83')"},{"name":"expected_status","value":"200"}],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":5,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":1,"attachmentsCount":5,"hasContent":true,"attachmentStep":false}],"testStage":{"description":"Проверяем удаление ранее добавленного элемента из избранного.","status":"failed","statusMessage":"Failed: КРИТИЧЕСКАЯ ОШИБКА: He удалось выполнить сессионный логин для пользователя testUser4@test.com. Ошибка: The status was pending 200, but received 500. URL: http://localhost:4040/api/auth\nBody of the answer:\nPlanned Server Error","statusTrace":"The status was pending 200, but received 500. URL: http://localhost:4040/api/auth\nBody of the answer:\nPlanned Server Error\n\nDuring handling of the above exception, another exception occurred:\nКРИТИЧЕСКАЯ ОШИБКА: He удалось выполнить сессионный логин для пользователя testUser4@test.com. Ошибка: The status was pending 200, but received 500. URL: http://localhost:4040/api/auth\nBody of the answer:\nPlanned Server Error","steps":[],"attachments":[{"uid":"411a51432b2a9d17","name":"log","source":"411a51432b2a9d17.txt","type":"text/plain","size":495},{"uid":"cc171c4a727d15b2","name":"stderr","source":"cc171c4a727d15b2.txt","type":"text/plain","size":583}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"authenticated_api_req_context::0","time":{"start":1746737207272,"stop":1746737207281,"duration":9},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"api_request_context::0","time":{"start":1746737208070,"stop":1746737208080,"duration":10},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"playwright_instance::0","time":{"start":1746737208080,"stop":1746737208088,"duration":8},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"epic","value":"Управление пользователем"},{"name":"severity","value":"normal"},{"name":"story","value":"Удаление из избранного"},{"name":"feature","value":"Избранное пользователя (DELETE /api/user/favourites/{id})"},{"name":"tag","value":"@pytest.mark.usefixtures('setup_favourite')"},{"name":"tag","value":"positive"},{"name":"tag","value":"user"},{"name":"parentSuite","value":"tests.user"},{"name":"suite","value":"test_user_api"},{"name":"subSuite","value":"TestUserAPI"},{"name":"host","value":"fv-az1380-461"},{"name":"thread","value":"9-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.user.test_user_api"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":["@pytest.mark.usefixtures('setup_favourite')","positive","user"]},"source":"a0b508da4074a001.json","parameterValues":[]}